var annotated =
[
    [ "Animation", "classAnimation.html", "classAnimation" ],
    [ "AudioHandler", "classAudioHandler.html", "classAudioHandler" ],
    [ "Camera", "classCamera.html", "classCamera" ],
    [ "Collision", "classCollision.html", "classCollision" ],
    [ "Configuration", "classConfiguration.html", "classConfiguration" ],
    [ "ControllerHandler", "classControllerHandler.html", "classControllerHandler" ],
    [ "Game", "classGame.html", "classGame" ],
    [ "GameObject", "classGameObject.html", "classGameObject" ],
    [ "GStatePlaceholder", "classGStatePlaceholder.html", "classGStatePlaceholder" ],
    [ "InputHandler", "classInputHandler.html", "classInputHandler" ],
    [ "Logger", "classLogger.html", "classLogger" ],
    [ "Music", "classMusic.html", "classMusic" ],
    [ "MusicManager", "classMusicManager.html", "classMusicManager" ],
    [ "Renderer", "classRenderer.html", "classRenderer" ],
    [ "ResourceHandler", "classResourceHandler.html", "classResourceHandler" ],
    [ "ResourceManager< Type >", "classResourceManager.html", "classResourceManager" ],
    [ "SFXManager", "classSFXManager.html", "classSFXManager" ],
    [ "SoundEffect", "classSoundEffect.html", "classSoundEffect" ],
    [ "Sprite", "classSprite.html", "classSprite" ],
    [ "SpriteManager", "classSpriteManager.html", "classSpriteManager" ],
    [ "StateGame", "classStateGame.html", "classStateGame" ],
    [ "Text", "classText.html", "classText" ],
    [ "Uncopyable", "classUncopyable.html", "classUncopyable" ],
    [ "Util", "classUtil.html", "classUtil" ],
    [ "Window", "classWindow.html", "classWindow" ]
];